### ISSUE TITLE
Sql output for Oracle 11

### ISSUE THREAD

**Issue by ebett** [ondras/wwwsqldesigner#196] opened 2015-04-27 11:18 UTC
Hi, This xsl for oracle doesn't work for oracle 11. For example auto_increment, comments are wrong.

```
<?xml version="1.0" ?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:output method="text"/>

<xsl:template name="replace-substring">
      <xsl:param name="value" />
      <xsl:param name="from" />
      <xsl:param name="to" />
      <xsl:choose>
         <xsl:when test="contains($value,$from)">
            <xsl:value-of select="substring-before($value,$from)" />
            <xsl:value-of select="$to" />
            <xsl:call-template name="replace-substring">
               <xsl:with-param name="value" select="substring-after($value,$from)" />
               <xsl:with-param name="from" select="$from" />
               <xsl:with-param name="to" select="$to" />
            </xsl:call-template>
         </xsl:when>
         <xsl:otherwise>
            <xsl:value-of select="$value" />
         </xsl:otherwise>
      </xsl:choose>
</xsl:template>

<xsl:template match="/sql">

<!-- tables -->
    <xsl:for-each select="table">
        <xsl:text>CREATE TABLE `</xsl:text>
        <xsl:value-of select="@name" />
        <xsl:text>` (
</xsl:text>
        <xsl:for-each select="row">
            <xsl:text>`</xsl:text>
            <xsl:value-of select="@name" />
            <xsl:text>` </xsl:text>

            <xsl:value-of select="datatype" />
            <xsl:text> </xsl:text>

            <xsl:if test="@null = 0">
                <xsl:text>NOT NULL </xsl:text>
            </xsl:if> 

            <xsl:if test="@autoincrement = 1">
                <xsl:text>AUTO_INCREMENT </xsl:text>
            </xsl:if> 

            <xsl:if test="default">
                <xsl:text>DEFAULT </xsl:text>
                <xsl:value-of select="default" />
                <xsl:text> </xsl:text>
            </xsl:if>

            <xsl:if test="comment">
                <xsl:text>COMMENT '</xsl:text>
                <xsl:call-template name="replace-substring">
                    <xsl:with-param name="value" select="comment" />
                    <xsl:with-param name="from" select='"&apos;"' />
                    <xsl:with-param name="to" select='"&apos;&apos;"' />
                </xsl:call-template>
                <xsl:text>' </xsl:text>
            </xsl:if>

            <xsl:if test="not (position()=last())">
                <xsl:text>,
</xsl:text>
            </xsl:if> 
        </xsl:for-each>

<!-- keys -->
        <xsl:for-each select="key">
            <xsl:text>,
</xsl:text>
            <xsl:choose>
                <xsl:when test="@type = 'PRIMARY'">PRIMARY KEY (</xsl:when>
                <xsl:when test="@type = 'FULLTEXT'">FULLTEXT KEY (</xsl:when>
                <xsl:when test="@type = 'UNIQUE'">UNIQUE KEY (</xsl:when>
                <xsl:otherwise>KEY (</xsl:otherwise>
            </xsl:choose>

            <xsl:for-each select="part">
                <xsl:text>`</xsl:text><xsl:value-of select="." /><xsl:text>`</xsl:text>
                <xsl:if test="not (position() = last())">
                    <xsl:text>, </xsl:text>
                </xsl:if>
            </xsl:for-each>
            <xsl:text>)</xsl:text>

        </xsl:for-each>

        <xsl:text>
)</xsl:text>

        <xsl:if test="comment">
            <xsl:text> COMMENT '</xsl:text>
            <xsl:call-template name="replace-substring">
                <xsl:with-param name="value" select="comment" />
                <xsl:with-param name="from" select='"&apos;"' />
                <xsl:with-param name="to" select='"&apos;&apos;"' />
            </xsl:call-template>
            <xsl:text>'</xsl:text>
        </xsl:if>

        <xsl:text>;

</xsl:text>

    </xsl:for-each>

<!-- fk -->
    <xsl:for-each select="table">
        <xsl:for-each select="row">
            <xsl:for-each select="relation">
                <xsl:text>ALTER TABLE `</xsl:text>
                <xsl:value-of select="../../@name" />
                <xsl:text>` ADD FOREIGN KEY (</xsl:text>
                <xsl:value-of select="../@name" />
                <xsl:text>) REFERENCES `</xsl:text>
                <xsl:value-of select="@table" />
                <xsl:text>` (`</xsl:text>
                <xsl:value-of select="@row" />
                <xsl:text>`);
</xsl:text>
            </xsl:for-each>
        </xsl:for-each>
    </xsl:for-each>

</xsl:template>
</xsl:stylesheet>
```

**Comment by ondras** [comment] 2015-04-27 11:33
Can you please provide:

1) an incorrect output,

2) a corrected version to see Oracle's syntax?

**Comment by ebett** [comment] 2015-04-27 11:40
Comments, and the rest of grammar are defined here
http://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_4009.htm#SQLRF01109

**Comment by ondras** [comment] 2015-04-28 13:07
I think I fixed those comments: https://github.com/ondras/wwwsqldesigner/commit/1bd2b93c6f5c988726ab5e4754bdc167b1f23b10

Can you please verify they are okay now?

As for AUTO_INCREMENT, this looks rather complex (sequences instead of a column attribute), so it might take some time.

**Comment by ebett** [comment] 2015-04-28 13:19
Ok, auto_increment does not exists in oracle, because it uses Sequence
objects. Don't worry about this, only remove auto_increment xml tag. The
rest is easy, we need  basic create table sentences with constraints and
comments.


2015-04-28 10:07 GMT-03:00 Ondřej Žára <notifications@github.com>:

**Comment by ebett** [comment] 2015-04-28 16:47
How to avoid empty comments?, I need to skip them

2015-04-28 10:19 GMT-03:00 Esteban Bett <estebanbett@gmail.com>:

**Comment by ondras** [comment] 2015-04-29 11:58
When I remove comments from my design (I set them to an empty string), there are no COMMENT sql statements generated - both for tables and columns. Can you please explain this in more detail, @ebett ?

**Comment by ebett** [comment] 2015-04-29 18:20
It's ok, sorry. =)


2015-04-29 8:58 GMT-03:00 Ondřej Žára <notifications@github.com>:

**Comment by ebett** [comment] 2015-04-30 13:11
Hi ondras, 
The column comment is wrong. I try change this "$table" for "../@name" and works ok.

**Comment by ebett** [comment] 2015-04-30 15:57
Another bug, in FK section:
When the parent table has two or more keys, te relation only write one of them in the references (...) list.
This bug cause the ORA-02270 error.

**Comment by ondras** [comment] 2015-05-04 09:28
> Hi ondras,
> The column comment is wrong. I try change this "$table" for "../@name" and works ok.

Hmm, seems to work for me. Can you please elaborate more?

**Comment by ondras** [comment] 2015-05-05 13:29
> Another bug, in FK section:
> When the parent table has two or more keys, te relation only write one of them in the references (...) list.
> This bug cause the ORA-02270 error.

This is basically a duplicate of https://github.com/ondras/wwwsqldesigner/issues/117.

**Comment by ondras** [comment] 2015-05-05 13:30
> Don't worry about this, only remove auto_increment xml tag.

Removed in 
https://github.com/ondras/wwwsqldesigner/commit/c831747a411fbd7b59957d2cdf1943db53394ee8

**Comment by cbarike** [comment] 2015-05-22 17:04
A few years ago I had added Oracle sequences and triggers for auto-increment functionality. This may not be fully up-to-date for the current version, but should get you started:
```SQL
<!-- create auto increment sequence -->
      <xsl:for-each select="row[@ai]">
        <xsl:text>CREATE SEQUENCE </xsl:text>
        <xsl:value-of select="$table" />
        <xsl:text>_SEQ</xsl:text>
        <xsl:value-of select="position()" />
        <xsl:text>
  START WITH 1 
  INCREMENT BY 1 
  CACHE 20 
  NOORDER  
  NOCYCLE
  NOMAXVALUE;

</xsl:text>
      </xsl:for-each>
<!-- create auto increment trigger -->
      <xsl:if test="0 &lt; count(row[@ai])">
        <xsl:text>CREATE OR REPLACE TRIGGER </xsl:text>
        <xsl:value-of select="$table" />
        <xsl:text>_BI
  before insert on </xsl:text>
        <xsl:value-of select="$table" />
        <xsl:text>
  for each row  
begin
</xsl:text>   
      <xsl:for-each select="row[@ai]">
        <xsl:text>    select </xsl:text>
        <xsl:value-of select="$table" />
        <xsl:text>_SEQ</xsl:text>
        <xsl:value-of select="position()" />
        <xsl:text>.nextval into :NEW.</xsl:text>
        <xsl:value-of select="title" />
        <xsl:text> from dual;
</xsl:text> 
      </xsl:for-each>
      <xsl:text>end; 
ALTER TRIGGER  </xsl:text>
      <xsl:value-of select="$table" />
      <xsl:text>_BI ENABLE;

</xsl:text>
      </xsl:if>
    </xsl:for-each>
```

**Comment by ondras** [comment] 2015-06-01 08:27
This is very cool, @cbarike . Would you mind sending a pull request now when WWW SQL Designer's main repo is hosted at GitHub?

**Comment by cbarike** [comment] 2015-06-02 21:09
Hi Ondřej,

Company policy currently keeps me from submitting a pull request, but the code posted above should be all you need to get the auto-increment functionality via sequence/trigger going in Oracle.

**Comment by ondras** [comment] 2017-01-02 08:14
Fixed in https://github.com/ondras/wwwsqldesigner/pull/238.

**Closed by ondras** 2017-01-02 08:14 UTC
