### ISSUE TITLE
Loads a blank screen in every browser

### ISSUE THREAD

**Issue by nfuller52** [ondras/wwwsqldesigner#199] opened 2015-06-12 20:30 UTC
I just pulled down the new changes and it doesn't load in any browser. I reverted to sha c831747 and it works in Firefox

**Comment by ondras** [comment] 2015-06-12 20:52
Damn. Well, I will investigate + fix - but not before Monday, as I will be gone for the whole weekend.

**Comment by CSiPet2** [comment] 2015-06-13 07:45
The problem is with toggle.js. It is included in the index.html, but not actually there.

**Comment by ondras** [comment] 2015-06-13 11:51
Yeah, I forgot to `git add` that file after splitting the app into individual components.

It should be noted, though, that the latest commit (the one that does not really work) does not bring any radially new features (and therefore one has no real motivation to pull it). It is a scaffolding for a reworked storage system that will allow greater flexibility with remote storage servers.

**Comment by ondras** [comment] 2015-06-15 06:50
Fixed in https://github.com/ondras/wwwsqldesigner/commit/dcea4c24e5efcb66cefb18eec8e7c9b596000867.

**Closed by ondras** 2015-06-15 06:50 UTC
